# Generated by Django 4.1.7 on 2023-05-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEspecialidad', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('idMedico', models.IntegerField(primary_key=True, serialize=False)),
                ('especialidad_idEspecialidad', models.ForeignKey(db_column='especialidad_idEspecialidad', on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('constraseña', models.CharField(max_length=45)),
                ('rut', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=45)),
                ('nro_telefono', models.IntegerField()),
                ('pacientecol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('precio', models.CharField(max_length=45)),
                ('fechaVenta', models.DateField()),
                ('idVenta', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('idtipoServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=45)),
                ('medico_idMedico', models.ForeignKey(db_column='medico_idMedico', on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
            options={
                'db_table': 'tipoServicio',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=45)),
                ('tipoServicio_idtipoServicio', models.ForeignKey(db_column='tipoServicio_idtipoServicio', on_delete=django.db.models.deletion.CASCADE, to='core.tiposervicio')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='ReservaHora',
            fields=[
                ('fecha', models.CharField(max_length=45)),
                ('idreservaHora', models.IntegerField(primary_key=True, serialize=False)),
                ('medico_idMedico', models.ForeignKey(db_column='medico_idMedico', on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('paciente_idUsuarios', models.ForeignKey(db_column='paciente_idUsuarios', on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('servicio_idservicio', models.ForeignKey(db_column='servicio_idservicio', on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
                ('venta_idVenta', models.ForeignKey(db_column='venta_idVenta', on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
            options={
                'db_table': 'reservaHora',
            },
        ),
    ]
