# Generated by Django 4.2.1 on 2023-05-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_recuperarpass',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
