# Generated by Django 4.1.7 on 2023-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_end_time_remove_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahora',
            name='hora',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
